server:
  port: 10001

spring:
  datasource:
    url: jdbc:mysql://bjfk-staging-d42.yz02:15733/wyj_test_db?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: test_rw
    password: 54rltyi5BCdcm06wu22A0brvvzU5uDgB
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql

  redis:
    host: 127.0.0.1 #47.98.221.42
    port: 6379
#    password: 123456 #68KjMkNBU3e
    timeout: 3000ms
    jedis:
      pool:
        max-active: 1000   #最大连接数
        max-wait: 3000ms #最大阻塞等待时间(负数表示没限制)
        max-idle: 200   #最大空闲
        min-idle: 0

distribute:
  deviceid:
    bit-length: 3
    host: "localhost:10001"
short-url:
  host: "localhost:10001"
