server:
  port: 10001

spring:
  datasource:
    url: jdbc:mysql://rm-bp11fo7r52fp6qc61xo.mysql.rds.aliyuncs.com:3306/student_card?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: W#EVI7921Kjl
    driver-class-name: com.mysql.jdbc.Driver
    platform: mysql

  redis:
    host: 192.168.0.60 #47.98.221.42
    port: 6379
    password: 123456 #68KjMkNBU3e
    timeout: 3000ms
    jedis:
      pool:
        max-active: 1000   #最大连接数
        max-wait: 3000ms #最大阻塞等待时间(负数表示没限制)
        max-idle: 200   #最大空闲
        min-idle: 0

distribute:
  deviceid:
    bit-length: 3
    host: "localhost:10001"
short-url:
  host: "localhost:10001"
